name: Update the latest branch
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/wc-create-pr-branch.yaml
    permissions:
      contents: write
    with:
      version: latest
