---
name: Release
run-name: Release ${{inputs.version}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
      pr:
        description: "pr number (pre-release)"
        required: false
jobs:
  release:
    uses: ./.github/workflows/wc-create-pr-branch.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      version: ${{inputs.version}}
      pr: ${{inputs.pr && fromJSON(inputs.pr) || ''}}
